<?php

define('FILTER', [
  '(saison complète)',
  'Enhanced Edition',
  ': Complete',
  'Redux',
  'Legacy Edition',
  '_',
  '.',
  ':',
  '™',
  'Sid Meier\'s',
  'Steam Special Edition',
  'Steam Edition',
  'Remastered',
  '(TM)',
  'Gold Edition',
  'Definitive Edition',
  'Maximum Edition',
  'Complete Edition',
  'Special Edition',
  "The Director's Cut",
  'Director\'s Cut',
  'E.Edition',
  'E. Edition',
  '[3DS]',
  '[PC]',
  '[iOS]',
  '[iOS-PC]',
  '[Xbox One]',
  '[Xbox 360]',
  '[Android-iOS-PC-Mac-Linux]',
  '[PlayStation 2]',
  '[PlayStation 4]',
  '[PlayStation 3]',
  '[PlayStation VR]',
  '[iOS-Nintendo 3DS-PC]',
  '[Oculus Rift]',
  '[Xbox One-PC]',
  '[Android-iOS]',
  '[Android-iOS-PC]',
  '[iOS-PC-Mac-Linux-tvOS]',
  '[iOS-PC-Mac]',
  '[PS Vita]',
  '[Android-iOS-Windows Phone-PC]',
  '[PlayStation 4-Xbox One]',
  '[PlayStation 4-PS Vita]',
  '[PlayStation 3-Xbox 360]',
  '[Windows Phone]',
  '[iOS-Windows Phone]',
  '[Android-iOS-PC-Mac]',
  '[Wii U]',
  '[Wii U-Xbox 360]',
  '[Switch]',
  '[New 3DS]',
  '[PS 5ita]',
  '®',
  '-',
  "'",
  '!',
  ' '
]);

define('COINCOIN2CPC', [
  '’Splosion Man' => 'Ms. Splosion Man [iOS-Windows Phone]',
  'Anhk 2' => 'Ankh 2 : Le Cœur d\'Osiris',
  'Animal Crossing New Horizons' => 'Animal Crossing : New Horizons [Switch]',
  'Back to the Future : Episode 3 - Citizen Brown' => 'Back to the Future - Episode 2/3 : Get Tannen/Citizen Brown',
  'Batman : The Telltale Series' => 'Batman : The Telltale Series (saison complète)',
  'Batman Arkham Knight' => 'Batman Arkham Knight',
  'Beatbuddy' => 'Beatbuddy : Tale of the Guardians',
  'Best of the Underground' => 'Best of the Underground (Geometry Wars, Rag Doll Kung Fu, Eets, Gumboy CA)',
  'Bokida - Heartfelt Reunion' => 'Bokida',
  'Broken Lines' => 'Broken Lines',
  'Burnout Paradise' => 'Burnout Paradise : The Ultimate Box',
  'Call of Duty : Warzone' => 'Call of Duty : Warzone',
  'Canis Canem Edit' => 'Canis Canem Edit [PlayStation 2]',
  'Command & Conquer - Red Alert 3 : Uprising' => 'Command & Conquer : Alerte Rouge 3 - La Révolte',
  'Command & Conquer 4 : Tiberian Twilight' => 'Command & Conquer 4 : Le Crépuscule du Tiberium',
  'Cosmic Express' => 'Cosmic Express [Android-iOS-PC-Mac-Linux]',
  'Costume Quest' => 'Costume Quest [PlayStation 3-Xbox 360]',
  'Darkness Within 2' => 'Darkness Within 2 : The Dark Lineage',
  'Deponia' => 'Deponia',
  'Depth' => 'Depth',
  'Destiny 2 sur PC' => 'Destiny 2',
  'Destiny : Les seigneurs de fer' => 'Destiny : Les Seigneurs de Fer [PlayStation 4-Xbox One]',
  'Disaster Report 4 : Summer Memories' => 'Disaster Report 4 : Summer Memories',
  'Dishonored : Dunwall City Trials' => 'Dishonored : Dunwall City Trains',
  'Dreamfall : The Longest Journey' => 'Dreamfall',
  'Eagle Flight' => 'Eagle Flight [Oculus Rift]',
  'Edna & Harvey s\'évadent' => 'Edna & Harvey : L\'Evasion',
  'Empire at War' => 'Star Wars : Empire at War',
  'F-Zero GP Legends' => 'F-Zero GP Legends [Wii U-Game Boy Advance]',
  'FIFA 2010' => 'FIFA 10',
  'Final Fantasy VII Remake' => 'Final Fantasy VII Remake [PlayStation 4]',
  'Full Throttle Remastered' => 'Full Throttle Remaster',
  'GTA IV' => 'Grand Theft Auto IV',
  'GTA V : le FPS' => 'Grand Theft Auto V',
  'GTR 2 - FIA GT Racing' => 'GTR 2',
  'Gabriel Knight : Sins of the Fathers' => 'Gabriel Knight : Sins of the Father : 20th Anniversary Edition',
  'Gang Land' => 'Gang Land : Trouble in Paradise',
  'Garshasp' => 'Garshasp : The Monster Slayer',
  'Guitar Hero III : Legends of Rock' => 'Guitar Hero III',
  'Half-Life : Alyx' => 'Half-Life : Alyx',
  'HarshQuad' => 'HarshQuad [Windows Phone]',
  'Hatsune Miku : Project Diva X' => 'Hatsune Miku : Project Diva F [PlayStation 3]',
  'Hell Yeah !' => 'Hell Yeah ! La Fureur du Lapin Mort',
  'Hitman' => 'Hitman - Game of the Year Edition',
  'Horizon\'s Gate' => 'Horizon\'s Gate',
  'Kentucky Route Zero : Act IV' => 'Kentucky Route Zero - Acte IV',
  'Knee Deep' => 'Knee Deep (saison complète)',
  'L.A. Noire' => 'L.A. Noire',
  'La Guerre de l\'Anneau' => 'Le Seigneur des Anneaux : La Guerre de l\'Anneau',
  'Life is Strange : Before the Storm – épisode 1' => 'Life is Strange : Before the Storm - Episode 1',
  'Marvel vs Capcom 3 : Fate of Two World' => 'Marvel vs Capcom 3 : Fate of Two Worlds [PlayStation 3-Xbox 360]',
  'Mercenaries 2 : World in Flames' => 'Mercenaries 2',
  'Moss' => 'Moss [PlayStation VR]',
  'Multiwinia' => 'Multiwinia : Survival of the Flattest',
  'Night of the Consumers' => 'Night of the Consumers',
  'Orwell : Ignorance is Strength' => 'Orwell : Ignorance is Strength (saison complète)',
  'PES 2013' => 'Pro Evolution Soccer 2013',
  'PES 2017' => 'Pro Evolution Soccer 2017',
  'PES 2019' => 'Pro Evolution Soccer 2019',
  'Peter Jackson\'s King Kong' => 'King Kong',
  'Pix the Cat' => 'Pix The Cat [PlayStation 4-PS Vita]',
  'Rayman Legends' => 'Rayman Legends [Wii U-Xbox 360]',
  'Recettear : An Item\'s Shop Tale' => 'Recettear',
  'Red Orchestra 2' => 'Red Orchestra : Ostfront 41-45',
  'Reservoir Dogs' => 'Reservoir Dogs',
  'Resident Evil 3' => 'Resident Evil 3',
  'Resident Evil 5' => 'Resident Evil 5',
  'Rise of Nations : Rise of Legends' => 'Rise of Legends',
  'Risen 2 : Dark Waters' => 'Risen 2',
  'Robinson : The Journey' => 'Robinson : The Journey [PlayStation VR]',
  'SBK09' => 'SBK 09 : Superbike World Championship',
  'Sam & Max The Devil\'s Playhouse - Episode 4 et 5' => 'Sam & Max Season 3 - Episode 4/5 : Beyond the Alley of the Dolls/The City That Dares Not Sleep',
  'Scarface' => 'Scarface : The World is Yours',
  'Silent Hunter IV : Wolves of the Pacific' => 'Silent Hunter IV : Wolves of the Pacific - U-Boat Missions',
  'SimAirport' => 'SimAirport',
  'Simon the Sorcerer 4 : Chaos Happens' => 'Simon le Sorcier 4 : En Proie au Chaos',
  'Skyrim Special Edition' => 'Skyrim Special Edition',
  'Sleep is Death' => 'Sleep is Death (Geisterfahrer)',
  'Space Shuttle pour Flight Sim X' => 'Space Shuttle',
  'Split/Second' => 'Split/Second Velocity',
  'Stacking' => 'Stacking',
  'Strong Bad\'s Cool Game for Attractive People Episode 2: Strong Badia for the Free' => 'Strong Bad\'s Cool Game for Attractive People : Strong Badia the Free',
  'Strong Bad\'s Cool Game for Attractive People Episode 3 : Dangereresque 3' => 'Strong Bad\'s Cool Game for Attractive People : Dangeresque 3',
  'Strong bad\'s cool Game for Attractive People' => 'Strong Bad\'s Cool Game for Attractive People Saison 1',
  'Stygian: Reign of the old ones' => 'Stygian : Reign of the Old Ones',
  'Super Smash Bros. for Nintendo 3DS' => 'Super Smash Bros [3DS]',
  'Sven : le mouton baiseur' => 'Sven : Le Mouton Baiseur (Sven Bømwøllen)',
  'The Incredible Hulk' => 'L\'Incroyable Hulk',
  'The Ship' => 'The Ship : Murder Party',
  'The Sims 2' => 'Les Sims 2',
  'The Walking Dead : The Game Episodes 4 et 5' => 'The Walking Dead : The Game - Episodes 4/5 : Around Every Corner/No Time Left',
  'The Witcher 3' => 'The Witcher 3 : Traque Sauvage',
  'Toca Race Driver 2 : The Ultimate Racing Simulator' => 'TOCA Race Driver 2',
  'Tom Clancy\'s H.A.W.X.' => 'H.A.W.X.',
  'Top Spin' => 'Top Spin',
  'Uncharted 3' => 'Uncharted 3 : L\'illusion de Drake [PlayStation 3]',
  'Velocity 2X' => 'Velocity 2X [PlayStation 4-PS Vita]',
  'WRC 2010' => 'WRC',
  'Wallace et Gromit : Fright of the Bumblebees' => 'Wallace & Gromit\'s Grand Adventures - Episode 1 : Fright of the Bumblebees',
]);
